# Header
menu:
  主页: /
  所有文章: /archives
  # 学习: /tags/react-native

# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/logo.jpeg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  阮一峰的博客: http://www.ruanyifeng.com/
  reactNative学习手册: https://github.com/ele828/react-native-guide
  redux试用: https://github.com/lewis617/react-redux-tutorial
  利炳根简书: http://www.jianshu.com/users/eaec1fc422e9/latest_articles

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我就是旺仔小馒头，专业卖萌30年…
